### PR TITLE
Pvc waterproofing

### PR DESCRIPTION
**Pull request by royduin**

### CODE REVIEW

**Comment by LordMike** [comment]
Did you test this? :)

**Comment by royduin** [comment]
No but I was getting errors because this option is missing. Changed it to another value for now.

**Comment by LordMike** [comment]
I was wondering if `pvc` was the right value. So if the error specifically says "can't map 'pvc' .. then it probably is correct.." :)

**Comment by LordMike** [comment]
I tested it - it's good.

**Comment by royduin** [comment]
The error was exactly that. First I though I'll create an issue but the fix was easy so I've created a PR but forgot to add the exact error. Thanks for merging! When will the Docker container be updated?

**Comment by LordMike** [comment]
I'm on the docker image right now. It's done in a few minutes.

**Comment by royduin** [comment]
Great, thanks! 😎

**Pull request merged**
